version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/oriongw8_bd
      SPRING_DATASOURCE_USERNAME: oriongw8_bd
      SPRING_DATASOURCE_PASSWORD: Citsv75
    depends_on:
      - mysql
    entrypoint: ["sh", "-c", "echo 'Waiting for MySQL to start...' && sleep 10 && java -jar app.jar"]


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: oriongw8_bd
      MYSQL_ROOT_PASSWORD: Citsv75
      MYSQL_USER: oriongw8_bd
      MYSQL_PASSWORD: Citsv75
    ports:
      - "3006:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
