version: '3'
services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/oriongw8_bd
      SPRING_DATASOURCE_USERNAME: oriongw8_bd
      SPRING_DATASOURCE_PASSWORD: Citsv75

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: oriongw8_bd
      MYSQL_ROOT_PASSWORD: Citsv75
    ports:
      - "3306:3306"
