server:
  port: 8081

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/oriongw8_bd?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: oriongw8_bd
      password: Citsv75
      driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/citlab24?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 123123
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        open-in-view: false
  thymeleaf:
    encoding: UTF-8
  flyway:
    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db/migration
